# Generated by Django 5.2.8 on 2025-11-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='angkatan',
            field=models.IntegerField(default=34, help_text='Contoh: 33, 34, 35', verbose_name='Angkatan'),
        ),
        migrations.AlterField(
            model_name='user',
            name='division',
            field=models.CharField(choices=[('JOURNALISM', 'Jurnalistik'), ('DESIGN', 'Design'), ('PHOTOGRAPHY', 'Fotografi')], default='JOURNALISM', max_length=20, verbose_name='Divisi'),
        ),
    ]
