# Generated by Django 5.2.8 on 2025-11-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='badge',
            field=models.CharField(blank=True, choices=[('', 'Tidak Ada'), ('PIC_DIVISI', 'PIC Divisi'), ('KETUA', 'Ketua Media Moklet'), ('WAKA', 'Wakil Ketua Media Moklet'), ('SEKRETARIS', 'Sekretaris'), ('BENDAHARA', 'Bendahara')], default='', max_length=20, verbose_name='Badge/Jabatan'),
        ),
    ]
