# Generated by Django 5.2.8 on 2025-11-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_badge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nama Badge')),
                ('slug', models.SlugField(unique=True)),
                ('color', models.CharField(default='blue', help_text='Warna badge: blue, green, red, purple, yellow, etc', max_length=20, verbose_name='Warna')),
                ('icon', models.CharField(default='⭐', max_length=50, verbose_name='Icon/Emoji')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='badge',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PIC_DIVISI', 'PIC Divisi'), ('KETUA', 'Ketua Media Moklet'), ('WAKA', 'Wakil Ketua'), ('SEKRETARIS', 'Sekretaris'), ('MEMBER', 'Anggota')], default='MEMBER', max_length=20, verbose_name='Role/Jabatan'),
        ),
        migrations.AddField(
            model_name='user',
            name='badges',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.badge', verbose_name='Badges'),
        ),
    ]
