# Generated by Django 5.2.8 on 2025-11-25 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nama Event')),
                ('date', models.DateTimeField(verbose_name='Tanggal & Waktu')),
                ('description', models.TextField(verbose_name='Deskripsi Singkat')),
                ('location', models.CharField(max_length=200, verbose_name='Lokasi')),
                ('needs_photo', models.BooleanField(default=False, verbose_name='Butuh Foto')),
                ('needs_video', models.BooleanField(default=False, verbose_name='Butuh Video')),
                ('needs_article', models.BooleanField(default=False, verbose_name='Butuh Artikel')),
                ('documentation_link', models.URLField(blank=True, verbose_name='Link Dokumentasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_events', to=settings.AUTH_USER_MODEL, verbose_name='Koordinator (PIC)')),
            ],
        ),
    ]
