# Generated by Django 5.2.8 on 2025-11-25 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul Konten')),
                ('content_type', models.CharField(choices=[('ARTICLE', 'Artikel'), ('VIDEO', 'Video'), ('DESIGN', 'Desain'), ('PODCAST', 'Podcast'), ('EVENT', 'Liputan Event')], max_length=20, verbose_name='Jenis Konten')),
                ('platform', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'YouTube'), ('WEBSITE', 'Website'), ('TIKTOK', 'TikTok')], max_length=20, verbose_name='Platform')),
                ('status', models.CharField(choices=[('IDEA', 'Ide'), ('IN_PROGRESS', 'Sedang Dikerjakan'), ('REVIEW', 'Review/Edit'), ('FINAL', 'Final'), ('UPLOADED', 'Diupload')], default='IDEA', max_length=20, verbose_name='Status')),
                ('target_date', models.DateField(verbose_name='Tanggal Target Post')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi/Brief')),
                ('draft_link', models.URLField(blank=True, verbose_name='Link Draft (Drive)')),
                ('final_link', models.URLField(blank=True, verbose_name='Link Final')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_contents', to=settings.AUTH_USER_MODEL, verbose_name='Penulis/Reporter')),
                ('designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designed_contents', to=settings.AUTH_USER_MODEL, verbose_name='Desainer/Videografer')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_contents', to=settings.AUTH_USER_MODEL, verbose_name='Editor')),
            ],
        ),
    ]
