# Generated by Django 5.2.8 on 2025-11-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='content_type',
            field=models.CharField(choices=[('MOTANYA', 'Motanya'), ('MELAPOR', 'Melapor'), ('PODCAST', 'Podcast'), ('BEMO', 'Bemo'), ('BESMO', 'Besmo'), ('IG_STORY', 'IG Story')], max_length=20, verbose_name='Jenis Konten'),
        ),
    ]
