# Generated by Django 5.2.8 on 2025-11-25 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_contentitem_content_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Content Item', 'verbose_name_plural': 'Content Items'},
        ),
        migrations.AddField(
            model_name='contentitem',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Waktu Diambil'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Diambil Oleh'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='documentation_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link Dokumentasi'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='is_claimable',
            field=models.BooleanField(default=False, help_text='Centang jika konten bisa diambil oleh member', verbose_name='Bisa Diambil?'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_content', to=settings.AUTH_USER_MODEL, verbose_name='Penulis'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='content_type',
            field=models.CharField(choices=[('MOTANYA', 'Motanya'), ('MELAPOR', 'Melapor'), ('PODCAST', 'Podcast'), ('BEMO', 'Bemo'), ('BESMO', 'Besmo'), ('IG_STORY', 'IG Story')], max_length=50, verbose_name='Jenis Konten'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Deskripsi'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designed_content', to=settings.AUTH_USER_MODEL, verbose_name='Desainer'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='draft_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link Draft'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_content', to=settings.AUTH_USER_MODEL, verbose_name='Editor'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='final_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link Final'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='platform',
            field=models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'YouTube'), ('TIKTOK', 'TikTok'), ('WEBSITE', 'Website')], max_length=50, verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='status',
            field=models.CharField(choices=[('IDEA', 'Ide'), ('IN_PROGRESS', 'Sedang Dikerjakan'), ('REVIEW', 'Review'), ('FINAL', 'Final'), ('UPLOADED', 'Diupload')], default='IDEA', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='target_date',
            field=models.DateField(blank=True, null=True, verbose_name='Target Tanggal'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Judul'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Membuat Konten'), ('CLAIMED', 'Mengambil Job'), ('COMPLETED', 'Menyelesaikan Konten'), ('COMMENTED', 'Berkomentar'), ('UPLOADED', 'Upload Konten')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.contentitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ContentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Komentar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cms.contentitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
