# Generated by Django 5.2.8 on 2025-11-25 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_contentitem_options_contentitem_claimed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Membuat Konten'), ('CLAIMED', 'Mengambil Job'), ('COMPLETED', 'Menyelesaikan Konten'), ('COMMENTED', 'Berkomentar'), ('UPLOADED', 'Upload Konten'), ('CLAIMED_ROLE', 'Mengambil Role')], max_length=20),
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('CAMERAMAN', '📷 Cameraman'), ('CAPTION_WRITER', '✍️ Caption Writer'), ('CONTENT_WRITER', '📝 Content Writer'), ('VIDEO_EDITOR', '🎬 Video Editor'), ('THUMBNAIL_DESIGNER', '🖼️ Thumbnail Designer'), ('TALENT', '🎭 Talent')], max_length=50, verbose_name='Jenis Role')),
                ('slots_needed', models.PositiveIntegerField(default=1, verbose_name='Jumlah Orang Dibutuhkan')),
                ('description', models.TextField(blank=True, help_text='Optional: Jelaskan detail role ini', verbose_name='Deskripsi Role')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_roles', to='cms.contentitem')),
            ],
            options={
                'verbose_name': 'Job Role',
                'verbose_name_plural': 'Job Roles',
                'unique_together': {('content', 'role_type')},
            },
        ),
        migrations.CreateModel(
            name='JobRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='cms.jobrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Role Assignment',
                'verbose_name_plural': 'Job Role Assignments',
                'unique_together': {('job_role', 'user')},
            },
        ),
    ]
